#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_AN0220

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "NikkiPhysics_structs.hpp"
#include "X6Game_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_AN0220.ABP_AN0220_C
// 0x1340 (0x1790 - 0x0450)
class UABP_AN0220_C final : public UNikkiClothAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0458(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0460(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0468(0x0020)()
	uint8                                         Pad_488[0x8];                                      // 0x0488(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_NikkiPhysics                 AnimGraphNode_NikkiPhysics;                        // 0x0490(0x11F0)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x1680(0x00B8)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x1738(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x1758(0x0020)()
	class UBP_CombatCrySmileComponent_C*          CrySmileComp;                                      // 0x1778(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        PyhsicsAlpha;                                      // 0x1780(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ABP_AN0220(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ABP_AN0220_C">();
	}
	static class UABP_AN0220_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_AN0220_C>();
	}
};
static_assert(alignof(UABP_AN0220_C) == 0x000010, "Wrong alignment on UABP_AN0220_C");
static_assert(sizeof(UABP_AN0220_C) == 0x001790, "Wrong size on UABP_AN0220_C");
static_assert(offsetof(UABP_AN0220_C, UberGraphFrame) == 0x000450, "Member 'UABP_AN0220_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimBlueprintExtension_PropertyAccess) == 0x000458, "Member 'UABP_AN0220_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimBlueprintExtension_Base) == 0x000460, "Member 'UABP_AN0220_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimGraphNode_Root) == 0x000468, "Member 'UABP_AN0220_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimGraphNode_NikkiPhysics) == 0x000490, "Member 'UABP_AN0220_C::AnimGraphNode_NikkiPhysics' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimGraphNode_LinkedInputPose) == 0x001680, "Member 'UABP_AN0220_C::AnimGraphNode_LinkedInputPose' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimGraphNode_LocalToComponentSpace) == 0x001738, "Member 'UABP_AN0220_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, AnimGraphNode_ComponentToLocalSpace) == 0x001758, "Member 'UABP_AN0220_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, CrySmileComp) == 0x001778, "Member 'UABP_AN0220_C::CrySmileComp' has a wrong offset!");
static_assert(offsetof(UABP_AN0220_C, PyhsicsAlpha) == 0x001780, "Member 'UABP_AN0220_C::PyhsicsAlpha' has a wrong offset!");

}

