#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_PlayerDefaultInteractionPerformance

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimGraph) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimGraph");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimGraph) == 0x000010, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimGraph");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimGraph, AnimGraph_0) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimGraph::AnimGraph_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimLayer_AttractorBehavior
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior final
{
public:
	struct FPoseLink                              InPose_AttractorBehavior;                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimLayer_AttractorBehavior_0;                     // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior, InPose_AttractorBehavior) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior::InPose_AttractorBehavior' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior, AnimLayer_AttractorBehavior_0) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_AttractorBehavior::AnimLayer_AttractorBehavior_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimLayer_CustomBehavior
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimLayer_CustomBehavior_0;                        // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior, InPose) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior::InPose' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior, AnimLayer_CustomBehavior_0) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_CustomBehavior::AnimLayer_CustomBehavior_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimLayer_DialogueBehavior
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior final
{
public:
	struct FPoseLink                              InPose_DIalogueBehavior;                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimLayer_DialogueBehavior_0;                      // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior, InPose_DIalogueBehavior) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior::InPose_DIalogueBehavior' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior, AnimLayer_DialogueBehavior_0) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_DialogueBehavior::AnimLayer_DialogueBehavior_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimLayer_InteractionPerformanceBehavior
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior final
{
public:
	struct FPoseLink                              InPose_InterationPerformance;                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimLayer_InteractionPerformanceBehavior_0;        // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior, InPose_InterationPerformance) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior::InPose_InterationPerformance' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior, AnimLayer_InteractionPerformanceBehavior_0) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_InteractionPerformanceBehavior::AnimLayer_InteractionPerformanceBehavior_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.AnimLayer_SituationFeedbackBehavior
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior final
{
public:
	struct FPoseLink                              InPose_SituationFeedback;                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimLayer_SituationFeedbackBehavior_0;             // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior, InPose_SituationFeedback) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior::InPose_SituationFeedback' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior, AnimLayer_SituationFeedbackBehavior_0) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_AnimLayer_SituationFeedbackBehavior::AnimLayer_SituationFeedbackBehavior_0' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation) == 0x000004, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation) == 0x000004, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation, DeltaTimeX) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_BlueprintUpdateAnimation::DeltaTimeX' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance
// 0x0068 (0x0068 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue; // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_32ByteByte_ReturnValue;        // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1; // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_1;     // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_32ByteByte_ReturnValue_1;      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2; // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue_2;     // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_26[0x2];                                       // 0x0026(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 CallFunc_GetComponentByClass_ReturnValue;          // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UBP_PlayerAnimStatesComponent_C*        CallFunc_GetComponentByClass_ReturnValue_1;        // 0x0040(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0049(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x004A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x004B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast;    // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1;  // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_2;  // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance) == 0x000068, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, EntryPoint) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::EntryPoint' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue) == 0x000004, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000008, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_EqualEqual_32ByteByte_ReturnValue) == 0x000009, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_EqualEqual_32ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1) == 0x00000C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_ReturnValue_1) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_EqualEqual_32ByteByte_ReturnValue_1) == 0x000011, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_EqualEqual_32ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_BooleanAND_ReturnValue) == 0x000012, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_BooleanAND_ReturnValue_1) == 0x000013, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue) == 0x000014, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2) == 0x000018, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GetRelevantAnimTimeRemaining_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_ReturnValue_2) == 0x00001C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, K2Node_Event_DeltaTimeX) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::K2Node_Event_DeltaTimeX' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_BooleanAND_ReturnValue_2) == 0x000024, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue_1) == 0x000025, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000028, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue_2) == 0x000030, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GetComponentByClass_ReturnValue) == 0x000038, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GetComponentByClass_ReturnValue_1) == 0x000040, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GetComponentByClass_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue_3) == 0x000048, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000049, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue_4) == 0x00004A, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_IsValid_ReturnValue_5) == 0x00004B, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast) == 0x000050, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1) == 0x000058, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_2) == 0x000060, "Member 'ABP_PlayerDefaultInteractionPerformance_C_ExecuteUbergraph_ABP_PlayerDefaultInteractionPerformance::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.InitializeFeedbackComponent
// 0x0018 (0x0018 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent final
{
public:
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_PlayerFeedBackPerformanceComponent_C* CallFunc_GetComponentByClass_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent) == 0x000018, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent, CallFunc_TryGetPawnOwner_ReturnValue) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent, CallFunc_GetComponentByClass_ReturnValue) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_InitializeFeedbackComponent::CallFunc_GetComponentByClass_ReturnValue' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.OnBecomeRelevant_OutputPose
// 0x0020 (0x0020 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose) == 0x000020, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose, Context) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose::Context' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose, Node) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_OutputPose::Node' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.OnBecomeRelevant_StanceSM
// 0x0038 (0x0038 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FAnimationStateMachineReference        CallFunc_ConvertToAnimationStateMachine_AnimationState; // 0x0020(0x0010)(NoDestructor)
	EAnimNodeReferenceConversionResult            CallFunc_ConvertToAnimationStateMachine_Result;    // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0031(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM) == 0x000038, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM, Context) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM::Context' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM, Node) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM::Node' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM, CallFunc_ConvertToAnimationStateMachine_AnimationState) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM::CallFunc_ConvertToAnimationStateMachine_AnimationState' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM, CallFunc_ConvertToAnimationStateMachine_Result) == 0x000030, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM::CallFunc_ConvertToAnimationStateMachine_Result' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM, K2Node_SwitchEnum_CmpSuccess) == 0x000031, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceSM::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.OnBecomeRelevant_StanceTransition
// 0x0050 (0x0050 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	EAnimNodeReferenceConversionResult            CallFunc_ConvertToSequencePlayer_Result;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSequencePlayerReference               CallFunc_ConvertToSequencePlayer_ReturnValue;      // 0x0028(0x0010)(NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSequencePlayerReference               CallFunc_SetAccumulatedTime_ReturnValue;           // 0x0040(0x0010)(NoDestructor)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition) == 0x000050, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, Context) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::Context' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, Node) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::Node' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, CallFunc_ConvertToSequencePlayer_Result) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::CallFunc_ConvertToSequencePlayer_Result' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, CallFunc_ConvertToSequencePlayer_ReturnValue) == 0x000028, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::CallFunc_ConvertToSequencePlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, K2Node_SwitchEnum_CmpSuccess) == 0x000038, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition, CallFunc_SetAccumulatedTime_ReturnValue) == 0x000040, "Member 'ABP_PlayerDefaultInteractionPerformance_C_OnBecomeRelevant_StanceTransition::CallFunc_SetAccumulatedTime_ReturnValue' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.Update Stance State Machine Config
// 0x0002 (0x0002 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config final
{
public:
	bool                                          CallFunc_EqualEqual_32ByteByte_ReturnValue;        // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config) == 0x000001, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config) == 0x000002, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config, CallFunc_EqualEqual_32ByteByte_ReturnValue) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config::CallFunc_EqualEqual_32ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_Stance_State_Machine_Config::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.Update_StanceSequencePlayer
// 0x00B0 (0x00B0 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	EAnimNodeReferenceConversionResult            CallFunc_ConvertToSequencePlayer_Result;           // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSequencePlayerReference               CallFunc_ConvertToSequencePlayer_ReturnValue;      // 0x0028(0x0010)(NoDestructor)
	class UAnimInstance*                          CallFunc_GetAnimInstance_ReturnValue;              // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetAccumulatedTime_ReturnValue;           // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_Blueprint_GetMainAnimInstance_ReturnValue; // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimSequenceBase*                      CallFunc_GetSequencePure_ReturnValue;              // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSequencePlayerReference               CallFunc_X6SetAccumulatedTime_ReturnValue;         // 0x0070(0x0010)(NoDestructor)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSequencePlayerReference               CallFunc_X6SetAccumulatedTime_ReturnValue_1;       // 0x0088(0x0010)(NoDestructor)
	double                                        K2Node_VariableSet_CurStanceAccumulatedTime_ImplicitCast; // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_X6SetAccumulatedTime_Time_ImplicitCast;   // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_X6SetAccumulatedTime_Time_ImplicitCast_1; // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer) == 0x0000B0, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, Context) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::Context' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, Node) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::Node' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_ConvertToSequencePlayer_Result) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_ConvertToSequencePlayer_Result' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_ConvertToSequencePlayer_ReturnValue) == 0x000028, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_ConvertToSequencePlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_GetAnimInstance_ReturnValue) == 0x000038, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_GetAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_GetAccumulatedTime_ReturnValue) == 0x000040, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_GetAccumulatedTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_Blueprint_GetMainAnimInstance_ReturnValue) == 0x000048, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_Blueprint_GetMainAnimInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x000050, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_GetSequencePure_ReturnValue) == 0x000058, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_GetSequencePure_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, K2Node_SwitchEnum_CmpSuccess) == 0x000060, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000068, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_X6SetAccumulatedTime_ReturnValue) == 0x000070, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_X6SetAccumulatedTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_GreaterEqual_DoubleDouble_ReturnValue) == 0x000080, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_GreaterEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_X6SetAccumulatedTime_ReturnValue_1) == 0x000088, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_X6SetAccumulatedTime_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, K2Node_VariableSet_CurStanceAccumulatedTime_ImplicitCast) == 0x000098, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::K2Node_VariableSet_CurStanceAccumulatedTime_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_Multiply_DoubleDouble_B_ImplicitCast) == 0x0000A0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_Multiply_DoubleDouble_B_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_X6SetAccumulatedTime_Time_ImplicitCast) == 0x0000A8, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_X6SetAccumulatedTime_Time_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer, CallFunc_X6SetAccumulatedTime_Time_ImplicitCast_1) == 0x0000AC, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StanceSequencePlayer::CallFunc_X6SetAccumulatedTime_Time_ImplicitCast_1' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.Update_StateMachineTransition
// 0x0058 (0x0058 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimationStateMachineReference        CallFunc_ConvertToAnimationStateMachinePure_AnimationState; // 0x0028(0x0010)(NoDestructor)
	bool                                          CallFunc_ConvertToAnimationStateMachinePure_Result; // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   Temp_name_Variable;                                // 0x003C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0044(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_Select_Default;                             // 0x004C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition) == 0x000008, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition) == 0x000058, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, Context) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::Context' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, Node) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::Node' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, Temp_bool_Variable) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, CallFunc_ConvertToAnimationStateMachinePure_AnimationState) == 0x000028, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::CallFunc_ConvertToAnimationStateMachinePure_AnimationState' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, CallFunc_ConvertToAnimationStateMachinePure_Result) == 0x000038, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::CallFunc_ConvertToAnimationStateMachinePure_Result' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, Temp_name_Variable) == 0x00003C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, CallFunc_Array_Get_Item) == 0x000044, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition, K2Node_Select_Default) == 0x00004C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_Update_StateMachineTransition::K2Node_Select_Default' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.UpdateAdjustSittingPostureState
// 0x0550 (0x0550 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState final
{
public:
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Vector_IsNearlyZero_ReturnValue;          // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetCurveValue_ReturnValue;                // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_1;       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetCurveValue_ReturnValue_1;              // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_2;       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Vector_IsNearlyZero_ReturnValue_1;        // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue_3;       // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector_X;                            // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_2;                          // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_2;                          // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_2;                          // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Vector_IsNearlyZero_ReturnValue_2;        // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0089(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_8A[0x2];                                       // 0x008A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetCurveValue_ReturnValue_2;              // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue;           // 0x0090(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class USkeletalMeshComponent*>         CallFunc_K2_GetComponentsByClass_ReturnValue;      // 0x00F8(0x0010)(ReferenceParm, ContainsInstancedReference)
	class USkeletalMeshComponent*                 CallFunc_Array_Get_Item;                           // 0x0108(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 CallFunc_Array_Get_Item_1;                         // 0x0110(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetPostProcessInstance_ReturnValue;       // 0x0118(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimInstance*                          CallFunc_GetPostProcessInstance_ReturnValue_1;     // 0x0120(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetNikkiPhysicsClothThickness_ReturnValue; // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_1; // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0140(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x0158(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0171(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0172(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0173(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_4;                 // 0x0174(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_175[0x3];                                      // 0x0175(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class USkeletalMeshComponent*                 CallFunc_Array_Get_Item_2;                         // 0x0178(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAnimInstance*                          CallFunc_GetPostProcessInstance_ReturnValue_2;     // 0x0188(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0190(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0191(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0192(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_193[0x1];                                      // 0x0193(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_2; // 0x0194(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_5;                 // 0x0198(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_199[0x7];                                      // 0x0199(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_2;           // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_2;                 // 0x01A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x01C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x01CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsNotEmpty_ReturnValue;             // 0x01CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1CE[0x2];                                      // 0x01CE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Map_Find_Value;                           // 0x01D0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_231[0xF];                                      // 0x0231(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Map_Find_Value_1;                         // 0x0240(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_1;                   // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2A1[0xF];                                      // 0x02A1(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_Map_Find_Value_2;                         // 0x02B0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue_2;                   // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_311[0xF];                                      // 0x0311(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_K2_GetComponentToWorld_ReturnValue;       // 0x0320(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_InvertTransform_ReturnValue;              // 0x0380(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue;            // 0x03E0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0440(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_441[0xF];                                      // 0x0441(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue_1;          // 0x0450(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_ComposeTransforms_ReturnValue_2;          // 0x04B0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0510(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_6;                 // 0x0511(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_512[0x6];                                      // 0x0512(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0518(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast_1;    // 0x0520(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        K2Node_VariableSet_AdjustSittingPostureIK_Alpha_ImplicitCast; // 0x0528(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast;          // 0x0530(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast_1;        // 0x0538(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_A_ImplicitCast_2;        // 0x0540(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState) == 0x000010, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState) == 0x000550, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Loop_Counter_Variable) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x000004, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Loop_Counter_Variable_1) == 0x00000C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_IntInt_ReturnValue_1) == 0x000010, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Array_Index_Variable) == 0x000014, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Array_Index_Variable_1) == 0x000018, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Loop_Counter_Variable_2) == 0x00001C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_IntInt_ReturnValue_2) == 0x000020, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, Temp_int_Array_Index_Variable_2) == 0x000024, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Vector_IsNearlyZero_ReturnValue) == 0x000028, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Vector_IsNearlyZero_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetCurveValue_ReturnValue) == 0x00002C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetCurveValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_ReturnValue_1) == 0x000030, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetCurveValue_ReturnValue_1) == 0x000034, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetCurveValue_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_ReturnValue_2) == 0x000038, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Vector_IsNearlyZero_ReturnValue_1) == 0x000039, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Vector_IsNearlyZero_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue) == 0x00003A, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_ReturnValue_3) == 0x00003B, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_X) == 0x000040, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Y) == 0x000048, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Z) == 0x000050, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_X_1) == 0x000058, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Y_1) == 0x000060, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Z_1) == 0x000068, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_X_2) == 0x000070, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_X_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Y_2) == 0x000078, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Y_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BreakVector_Z_2) == 0x000080, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BreakVector_Z_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Vector_IsNearlyZero_ReturnValue_2) == 0x000088, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Vector_IsNearlyZero_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_1) == 0x000089, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetCurveValue_ReturnValue_2) == 0x00008C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetCurveValue_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetSocketTransform_ReturnValue) == 0x000090, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetSocketTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_TryGetPawnOwner_ReturnValue) == 0x0000F0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_TryGetPawnOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_K2_GetComponentsByClass_ReturnValue) == 0x0000F8, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_K2_GetComponentsByClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Get_Item) == 0x000108, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Get_Item_1) == 0x000110, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetPostProcessInstance_ReturnValue) == 0x000118, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetPostProcessInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetPostProcessInstance_ReturnValue_1) == 0x000120, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetPostProcessInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetNikkiPhysicsClothThickness_ReturnValue) == 0x000128, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetNikkiPhysicsClothThickness_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_1) == 0x00012C, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000130, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_ReturnValue_1) == 0x000138, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_MakeVector_ReturnValue) == 0x000140, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_MakeVector_ReturnValue_1) == 0x000158, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue) == 0x000170, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue_1) == 0x000171, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_2) == 0x000172, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_3) == 0x000173, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_4) == 0x000174, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Get_Item_2) == 0x000178, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Length_ReturnValue) == 0x000180, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetPostProcessInstance_ReturnValue_2) == 0x000188, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetPostProcessInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Less_IntInt_ReturnValue) == 0x000190, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue_2) == 0x000191, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue_3) == 0x000192, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_2) == 0x000194, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_GetNikkiPhysicsClothThickness_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_5) == 0x000198, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_ReturnValue_2) == 0x0001A0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_MakeVector_ReturnValue_2) == 0x0001A8, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_MakeVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Length_ReturnValue_1) == 0x0001C0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Less_IntInt_ReturnValue_1) == 0x0001C4, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_Length_ReturnValue_2) == 0x0001C8, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Less_IntInt_ReturnValue_2) == 0x0001CC, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Array_IsNotEmpty_ReturnValue) == 0x0001CD, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Array_IsNotEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_Value) == 0x0001D0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_ReturnValue) == 0x000230, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_Value_1) == 0x000240, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_Value_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_ReturnValue_1) == 0x0002A0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_Value_2) == 0x0002B0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_Value_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Map_Find_ReturnValue_2) == 0x000310, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Map_Find_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_K2_GetComponentToWorld_ReturnValue) == 0x000320, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_K2_GetComponentToWorld_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_InvertTransform_ReturnValue) == 0x000380, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_InvertTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_ComposeTransforms_ReturnValue) == 0x0003E0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_ComposeTransforms_ReturnValue' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue_4) == 0x000440, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_ComposeTransforms_ReturnValue_1) == 0x000450, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_ComposeTransforms_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_ComposeTransforms_ReturnValue_2) == 0x0004B0, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_ComposeTransforms_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_IsValid_ReturnValue_5) == 0x000510, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_BooleanAND_ReturnValue_6) == 0x000511, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_BooleanAND_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_A_ImplicitCast) == 0x000518, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Greater_DoubleDouble_A_ImplicitCast_1) == 0x000520, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Greater_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, K2Node_VariableSet_AdjustSittingPostureIK_Alpha_ImplicitCast) == 0x000528, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::K2Node_VariableSet_AdjustSittingPostureIK_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_A_ImplicitCast) == 0x000530, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_A_ImplicitCast_1) == 0x000538, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState, CallFunc_Add_DoubleDouble_A_ImplicitCast_2) == 0x000540, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateAdjustSittingPostureState::CallFunc_Add_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.UpdateCacheIndex
// 0x0004 (0x0004 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex final
{
public:
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex) == 0x000004, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex) == 0x000004, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex, CallFunc_Subtract_IntInt_ReturnValue) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateCacheIndex::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");

// Function ABP_PlayerDefaultInteractionPerformance.ABP_PlayerDefaultInteractionPerformance_C.UpdateStanceChange
// 0x0001 (0x0001 - 0x0000)
struct ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange final
{
public:
	bool                                          CallFunc_NotEqual_GameplayTag_ReturnValue;         // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange) == 0x000001, "Wrong alignment on ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange");
static_assert(sizeof(ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange) == 0x000001, "Wrong size on ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange");
static_assert(offsetof(ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange, CallFunc_NotEqual_GameplayTag_ReturnValue) == 0x000000, "Member 'ABP_PlayerDefaultInteractionPerformance_C_UpdateStanceChange::CallFunc_NotEqual_GameplayTag_ReturnValue' has a wrong offset!");

}

