#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimStates_CannotTransitionInStylized

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimStates_CannotTransitionInStylized.AnimStates_CannotTransitionInStylized_C
// 0x0000 (0x0030 - 0x0030)
class UAnimStates_CannotTransitionInStylized_C final : public UAnimNotifyState
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimStates_CannotTransitionInStylized_C">();
	}
	static class UAnimStates_CannotTransitionInStylized_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimStates_CannotTransitionInStylized_C>();
	}
};
static_assert(alignof(UAnimStates_CannotTransitionInStylized_C) == 0x000008, "Wrong alignment on UAnimStates_CannotTransitionInStylized_C");
static_assert(sizeof(UAnimStates_CannotTransitionInStylized_C) == 0x000030, "Wrong size on UAnimStates_CannotTransitionInStylized_C");

}

