#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BKMediaCustomTrack

#include "Basic.hpp"

#include "X6CustomizableSequencerTracks_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BKMediaCustomTrack.BKMediaCustomTrack_C
// 0x0000 (0x0100 - 0x0100)
class UBKMediaCustomTrack_C final : public UX6SequencerTrackBP
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BKMediaCustomTrack_C">();
	}
	static class UBKMediaCustomTrack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBKMediaCustomTrack_C>();
	}
};
static_assert(alignof(UBKMediaCustomTrack_C) == 0x000008, "Wrong alignment on UBKMediaCustomTrack_C");
static_assert(sizeof(UBKMediaCustomTrack_C) == 0x000100, "Wrong size on UBKMediaCustomTrack_C");

}

