#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AgentTask_BellAttractAnimal

#include "Basic.hpp"

#include "BP_AgentTaskMoveBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AgentTask_BellAttractAnimal.BP_AgentTask_BellAttractAnimal_C
// 0x0008 (0x0040 - 0x0038)
class UBP_AgentTask_BellAttractAnimal_C final : public UBP_AgentTaskMoveBase_C
{
public:
	class UNiagaraSystem*                         AttractNiagara;                                    // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AgentTask_BellAttractAnimal_C">();
	}
	static class UBP_AgentTask_BellAttractAnimal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AgentTask_BellAttractAnimal_C>();
	}
};
static_assert(alignof(UBP_AgentTask_BellAttractAnimal_C) == 0x000008, "Wrong alignment on UBP_AgentTask_BellAttractAnimal_C");
static_assert(sizeof(UBP_AgentTask_BellAttractAnimal_C) == 0x000040, "Wrong size on UBP_AgentTask_BellAttractAnimal_C");
static_assert(offsetof(UBP_AgentTask_BellAttractAnimal_C, AttractNiagara) == 0x000038, "Member 'UBP_AgentTask_BellAttractAnimal_C::AttractNiagara' has a wrong offset!");

}

