#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuoyancyBoatComponent

#include "Basic.hpp"

#include "BP_BuoyancyBoatComponent_classes.hpp"
#include "BP_BuoyancyBoatComponent_parameters.hpp"


namespace SDK
{

// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.DebugPontoons
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_BuoyancyBoatComponent_C::DebugPontoons()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "DebugPontoons");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.ExecuteUbergraph_BP_BuoyancyBoatComponent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::ExecuteUbergraph_BP_BuoyancyBoatComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "ExecuteUbergraph_BP_BuoyancyBoatComponent");

	Params::BP_BuoyancyBoatComponent_C_ExecuteUbergraph_BP_BuoyancyBoatComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.GetCapVolume
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  H                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  R                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 V                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::GetCapVolume(double H, double R, double* V)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "GetCapVolume");

	Params::BP_BuoyancyBoatComponent_C_GetCapVolume Parms{};

	Parms.H = H;
	Parms.R = R;

	UObject::ProcessEvent(Func, &Parms);

	if (V != nullptr)
		*V = Parms.V;
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.GetSpghereUnderPlaneVolume
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Distance                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Radius                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 V                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::GetSpghereUnderPlaneVolume(double Distance, double Radius, double* V)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "GetSpghereUnderPlaneVolume");

	Params::BP_BuoyancyBoatComponent_C_GetSpghereUnderPlaneVolume Parms{};

	Parms.Distance = Distance;
	Parms.Radius = Radius;

	UObject::ProcessEvent(Func, &Parms);

	if (V != nullptr)
		*V = Parms.V;
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.GetSphereVolume
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  R                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 V                                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::GetSphereVolume(double R, double* V)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "GetSphereVolume");

	Params::BP_BuoyancyBoatComponent_C_GetSphereVolume Parms{};

	Parms.R = R;

	UObject::ProcessEvent(Func, &Parms);

	if (V != nullptr)
		*V = Parms.V;
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_BuoyancyBoatComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "ReceiveTick");

	Params::BP_BuoyancyBoatComponent_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.UpdateBuoyancy
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FBS_FluxBuoyancyPontoon&   BuoyancyData                                           (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   InitPos                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::UpdateBuoyancy(double DeltaTime, const struct FBS_FluxBuoyancyPontoon& BuoyancyData, const struct FVector& InitPos)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "UpdateBuoyancy");

	Params::BP_BuoyancyBoatComponent_C_UpdateBuoyancy Parms{};

	Parms.DeltaTime = DeltaTime;
	Parms.BuoyancyData = std::move(BuoyancyData);
	Parms.InitPos = std::move(InitPos);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.GetOwnerMesh
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UPrimitiveComponent**             Output_Get                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_BuoyancyBoatComponent_C::GetOwnerMesh(class UPrimitiveComponent** Output_Get) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "GetOwnerMesh");

	Params::BP_BuoyancyBoatComponent_C_GetOwnerMesh Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output_Get != nullptr)
		*Output_Get = Parms.Output_Get;
}


// Function BP_BuoyancyBoatComponent.BP_BuoyancyBoatComponent_C.GetPontoonsLocations
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// TArray<struct FVector>*                 Locations                                              (Parm, OutParm)

void UBP_BuoyancyBoatComponent_C::GetPontoonsLocations(TArray<struct FVector>* Locations) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuoyancyBoatComponent_C", "GetPontoonsLocations");

	Params::BP_BuoyancyBoatComponent_C_GetPontoonsLocations Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Locations != nullptr)
		*Locations = std::move(Parms.Locations);
}

}

