#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DefaultPlayerPawn

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DefaultPlayerPawn.BP_DefaultPlayerPawn_C
// 0x0008 (0x0438 - 0x0430)
class ABP_DefaultPlayerPawn_C final : public APawn
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0430(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DefaultPlayerPawn_C">();
	}
	static class ABP_DefaultPlayerPawn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DefaultPlayerPawn_C>();
	}
};
static_assert(alignof(ABP_DefaultPlayerPawn_C) == 0x000008, "Wrong alignment on ABP_DefaultPlayerPawn_C");
static_assert(sizeof(ABP_DefaultPlayerPawn_C) == 0x000438, "Wrong size on ABP_DefaultPlayerPawn_C");
static_assert(offsetof(ABP_DefaultPlayerPawn_C, DefaultSceneRoot) == 0x000430, "Member 'ABP_DefaultPlayerPawn_C::DefaultSceneRoot' has a wrong offset!");

}

