#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FlyItemDataAsset

#include "Basic.hpp"

#include "BP_BulletDataAsset_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FlyItemDataAsset.BP_FlyItemDataAsset_C
// 0x0000 (0x01B8 - 0x01B8)
class UBP_FlyItemDataAsset_C final : public UBP_BulletDataAsset_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FlyItemDataAsset_C">();
	}
	static class UBP_FlyItemDataAsset_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_FlyItemDataAsset_C>();
	}
};
static_assert(alignof(UBP_FlyItemDataAsset_C) == 0x000008, "Wrong alignment on UBP_FlyItemDataAsset_C");
static_assert(sizeof(UBP_FlyItemDataAsset_C) == 0x0001B8, "Wrong size on UBP_FlyItemDataAsset_C");

}

