#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Prop_MusicBrick_Element

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Prop_MusicBrick_Element.BP_Prop_MusicBrick_Element_C
// 0x0050 (0x03F8 - 0x03A8)
class ABP_Prop_MusicBrick_Element_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      ActivateEffect;                                    // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      BoomEffect;                                        // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   mesh;                                              // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          CrashReceiver;                                     // 0x03C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        CrashCollision;                                    // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBP_ReceiveSkillWithTransformComponent_C* BP_ReceiveSkillWithTransformComponent;           // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        Distance;                                          // 0x03E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCrash;                                           // 0x03F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__BP_Prop_MusicBrick_Element_BP_ReceiveSkillWithTransformComponent_K2Node_ComponentBoundEvent_0_OnReceiveCrashWithoutEntity__DelegateSignature(class AActor* Attacker, class AActor* Instigater, const struct FVector& HitDirection, const struct FVector& HitLocation, class UActorComponent* HitComponent, const struct FHitResult& HitResult);
	void CrashAction();
	void ExecuteUbergraph_BP_Prop_MusicBrick_Element(int32 EntryPoint);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Prop_MusicBrick_Element_C">();
	}
	static class ABP_Prop_MusicBrick_Element_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Prop_MusicBrick_Element_C>();
	}
};
static_assert(alignof(ABP_Prop_MusicBrick_Element_C) == 0x000008, "Wrong alignment on ABP_Prop_MusicBrick_Element_C");
static_assert(sizeof(ABP_Prop_MusicBrick_Element_C) == 0x0003F8, "Wrong size on ABP_Prop_MusicBrick_Element_C");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, UberGraphFrame) == 0x0003A8, "Member 'ABP_Prop_MusicBrick_Element_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, ActivateEffect) == 0x0003B0, "Member 'ABP_Prop_MusicBrick_Element_C::ActivateEffect' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, BoomEffect) == 0x0003B8, "Member 'ABP_Prop_MusicBrick_Element_C::BoomEffect' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, mesh) == 0x0003C0, "Member 'ABP_Prop_MusicBrick_Element_C::mesh' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, CrashReceiver) == 0x0003C8, "Member 'ABP_Prop_MusicBrick_Element_C::CrashReceiver' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, CrashCollision) == 0x0003D0, "Member 'ABP_Prop_MusicBrick_Element_C::CrashCollision' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, BP_ReceiveSkillWithTransformComponent) == 0x0003D8, "Member 'ABP_Prop_MusicBrick_Element_C::BP_ReceiveSkillWithTransformComponent' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, DefaultSceneRoot) == 0x0003E0, "Member 'ABP_Prop_MusicBrick_Element_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, Distance) == 0x0003E8, "Member 'ABP_Prop_MusicBrick_Element_C::Distance' has a wrong offset!");
static_assert(offsetof(ABP_Prop_MusicBrick_Element_C, IsCrash) == 0x0003F0, "Member 'ABP_Prop_MusicBrick_Element_C::IsCrash' has a wrong offset!");

}

