#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerEnvironmentEffectComponent

#include "Basic.hpp"

#include "BP_X6ActorComponent_classes.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerEnvironmentEffectComponent.BP_PlayerEnvironmentEffectComponent_C
// 0x0000 (0x00A8 - 0x00A8)
class UBP_PlayerEnvironmentEffectComponent_C final : public UBP_X6ActorComponent_C
{
public:
	void GetFloorPhysicsMateria(EPhysicalSurface* NewParam);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlayerEnvironmentEffectComponent_C">();
	}
	static class UBP_PlayerEnvironmentEffectComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerEnvironmentEffectComponent_C>();
	}
};
static_assert(alignof(UBP_PlayerEnvironmentEffectComponent_C) == 0x000008, "Wrong alignment on UBP_PlayerEnvironmentEffectComponent_C");
static_assert(sizeof(UBP_PlayerEnvironmentEffectComponent_C) == 0x0000A8, "Wrong size on UBP_PlayerEnvironmentEffectComponent_C");

}

