#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RMPTickRecord_InAir

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_RMPTickRecord_InAir.BP_RMPTickRecord_InAir_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct BP_RMPTickRecord_InAir_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
static_assert(alignof(BP_RMPTickRecord_InAir_C_GetModuleName) == 0x000008, "Wrong alignment on BP_RMPTickRecord_InAir_C_GetModuleName");
static_assert(sizeof(BP_RMPTickRecord_InAir_C_GetModuleName) == 0x000010, "Wrong size on BP_RMPTickRecord_InAir_C_GetModuleName");
static_assert(offsetof(BP_RMPTickRecord_InAir_C_GetModuleName, ReturnValue) == 0x000000, "Member 'BP_RMPTickRecord_InAir_C_GetModuleName::ReturnValue' has a wrong offset!");

}

