#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_MatchClothType_Head

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_MatchClothType_Head.E_MatchClothType_Head
// NumValues: 0x0004
enum class E_MatchClothType_Head : uint8
{
	NewEnumerator4                           = 0,
	NewEnumerator0                           = 1,
	NewEnumerator7                           = 2,
	E_MatchClothType_MAX                     = 3,
};

}

