#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Enum_InformTag

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum Enum_InformTag.Enum_InformTag
// NumValues: 0x0017
enum class Enum_InformTag : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator13                          = 3,
	NewEnumerator14                          = 4,
	NewEnumerator15                          = 5,
	NewEnumerator16                          = 6,
	NewEnumerator17                          = 7,
	NewEnumerator18                          = 8,
	NewEnumerator21                          = 9,
	NewEnumerator22                          = 10,
	NewEnumerator23                          = 11,
	NewEnumerator24                          = 12,
	NewEnumerator25                          = 13,
	NewEnumerator26                          = 14,
	NewEnumerator27                          = 15,
	NewEnumerator28                          = 16,
	NewEnumerator29                          = 17,
	NewEnumerator30                          = 18,
	NewEnumerator32                          = 19,
	NewEnumerator34                          = 20,
	NewEnumerator35                          = 21,
	Enum_MAX                                 = 22,
};

}

