#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FunctionLibrary_WeatherSys

#include "Basic.hpp"

#include "FunctionLibrary_WeatherSys_classes.hpp"
#include "FunctionLibrary_WeatherSys_parameters.hpp"


namespace SDK
{

// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.StorageTodsysActor
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerClass                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ABP_DyEnvSys_C**                  ref_TodSys                                             (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::StorageTodsysActor(class AActor* OwnerClass, class UObject* __WorldContext, class ABP_DyEnvSys_C** ref_TodSys)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "StorageTodsysActor");

	Params::FunctionLibrary_WeatherSys_C_StorageTodsysActor Parms{};

	Parms.OwnerClass = OwnerClass;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (ref_TodSys != nullptr)
		*ref_TodSys = Parms.ref_TodSys;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.FillVolumeTimeSpanList
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::FillVolumeTimeSpanList(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "FillVolumeTimeSpanList");

	Params::FunctionLibrary_WeatherSys_C_FillVolumeTimeSpanList Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.IsEditor Mode
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   inEditor                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::IsEditor_Mode(class UObject* __WorldContext, bool* inEditor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "IsEditor Mode");

	Params::FunctionLibrary_WeatherSys_C_IsEditor_Mode Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (inEditor != nullptr)
		*inEditor = Parms.inEditor;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Set Members in PPSettings
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPostProcessSettings&      StructRef                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FPostProcessSettings&      PostProcessSettings                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FPostProcessSettings*            StructOut                                              (Parm, OutParm)

void UFunctionLibrary_WeatherSys_C::Set_Members_in_PPSettings(const struct FPostProcessSettings& StructRef, const struct FPostProcessSettings& PostProcessSettings, class UObject* __WorldContext, struct FPostProcessSettings* StructOut)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "Set Members in PPSettings");

	Params::FunctionLibrary_WeatherSys_C_Set_Members_in_PPSettings Parms{};

	Parms.StructRef = std::move(StructRef);
	Parms.PostProcessSettings = std::move(PostProcessSettings);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (StructOut != nullptr)
		*StructOut = std::move(Parms.StructOut);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.DoesTodSysExist
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Ready                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::DoesTodSysExist(class UObject* __WorldContext, bool* Ready)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "DoesTodSysExist");

	Params::FunctionLibrary_WeatherSys_C_DoesTodSysExist Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Ready != nullptr)
		*Ready = Parms.Ready;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Stage Lighting
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// E_DeLightType                           LightType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ULightComponent*                  LightComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::Stage_Lighting(E_DeLightType LightType, class ULightComponent* LightComp, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "Stage Lighting");

	Params::FunctionLibrary_WeatherSys_C_Stage_Lighting Parms{};

	Parms.LightType = LightType;
	Parms.LightComp = LightComp;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Check Weather Volume State
// (Static, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADynamicWeatherVolume*            DESVolume                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::Check_Weather_Volume_State(class ADynamicWeatherVolume* DESVolume, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "Check Weather Volume State");

	Params::FunctionLibrary_WeatherSys_C_Check_Weather_Volume_State Parms{};

	Parms.DESVolume = DESVolume;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Is PC Platform Low
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UFunctionLibrary_WeatherSys_C::Is_PC_Platform_Low(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "Is PC Platform Low");

	Params::FunctionLibrary_WeatherSys_C_Is_PC_Platform_Low Parms{};

	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.IsGamePlayerInVolume
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   BoxExtent                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   InVolume                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::IsGamePlayerInVolume(class AActor* Target, const struct FVector& BoxExtent, class UObject* __WorldContext, bool* InVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "IsGamePlayerInVolume");

	Params::FunctionLibrary_WeatherSys_C_IsGamePlayerInVolume Parms{};

	Parms.Target = Target;
	Parms.BoxExtent = std::move(BoxExtent);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (InVolume != nullptr)
		*InVolume = Parms.InVolume;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.WriteTextureWithOverride
// (Static, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    TexturePath                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UTextureRenderTarget2D*           RenderTarget                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// ETextureCompressionSettings             CompressionSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UTexture2D*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class UTexture2D* UFunctionLibrary_WeatherSys_C::WriteTextureWithOverride(const class FString& TexturePath, class UTextureRenderTarget2D* RenderTarget, ETextureCompressionSettings CompressionSettings, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("FunctionLibrary_WeatherSys_C", "WriteTextureWithOverride");

	Params::FunctionLibrary_WeatherSys_C_WriteTextureWithOverride Parms{};

	Parms.TexturePath = std::move(TexturePath);
	Parms.RenderTarget = RenderTarget;
	Parms.CompressionSettings = CompressionSettings;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.DrawSourceCurve
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EBlendMode                              BlendMode                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Row                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRuntimeCurveLinearColor&  RuntimeCurve                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class UTextureRenderTarget2D*           TextureRenderTarget                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::DrawSourceCurve(EBlendMode BlendMode, double Row, const struct FRuntimeCurveLinearColor& RuntimeCurve, class UTextureRenderTarget2D* TextureRenderTarget, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "DrawSourceCurve");

	Params::FunctionLibrary_WeatherSys_C_DrawSourceCurve Parms{};

	Parms.BlendMode = BlendMode;
	Parms.Row = Row;
	Parms.RuntimeCurve = std::move(RuntimeCurve);
	Parms.TextureRenderTarget = TextureRenderTarget;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.CurveStepSize
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  U_Size                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double*                                 StepSize                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::CurveStepSize(double U_Size, class UObject* __WorldContext, double* StepSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "CurveStepSize");

	Params::FunctionLibrary_WeatherSys_C_CurveStepSize Parms{};

	Parms.U_Size = U_Size;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);

	if (StepSize != nullptr)
		*StepSize = Parms.StepSize;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Update Compute Fog To Final
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::Update_Compute_Fog_To_Final(class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "Update Compute Fog To Final");

	Params::FunctionLibrary_WeatherSys_C_Update_Compute_Fog_To_Final Parms{};

	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.UpdateFillLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULightComponent*                  LightComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::UpdateFillLight(class ULightComponent* LightComp, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "UpdateFillLight");

	Params::FunctionLibrary_WeatherSys_C_UpdateFillLight Parms{};

	Parms.LightComp = LightComp;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Update Street Lamp
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULightComponent*                  LightComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::Update_Street_Lamp(class ULightComponent* LightComp, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "Update Street Lamp");

	Params::FunctionLibrary_WeatherSys_C_Update_Street_Lamp Parms{};

	Parms.LightComp = LightComp;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.UpdateDES LocalLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULightComponent*                  LitComp                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// E_DeLightType                           LightType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::UpdateDES_LocalLight(class ULightComponent* LitComp, E_DeLightType LightType, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "UpdateDES LocalLight");

	Params::FunctionLibrary_WeatherSys_C_UpdateDES_LocalLight Parms{};

	Parms.LitComp = LitComp;
	Parms.LightType = LightType;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.DetectDecalLocation
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USceneComponent*                  Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Decal                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class UStaticMeshComponent*             Plane                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// double                                  TraceRadius                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   bUseDecal                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::DetectDecalLocation(class USceneComponent* Actor, class USceneComponent* Decal, class UStaticMeshComponent* Plane, double TraceRadius, class UObject* __WorldContext, bool* bUseDecal)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "DetectDecalLocation");

	Params::FunctionLibrary_WeatherSys_C_DetectDecalLocation Parms{};

	Parms.Actor = Actor;
	Parms.Decal = Decal;
	Parms.Plane = Plane;
	Parms.TraceRadius = TraceRadius;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);

	if (bUseDecal != nullptr)
		*bUseDecal = Parms.bUseDecal;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.Remapped1015p
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   InputPin                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double UFunctionLibrary_WeatherSys_C::Remapped1015p(float InputPin, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "Remapped1015p");

	Params::FunctionLibrary_WeatherSys_C_Remapped1015p Parms{};

	Parms.InputPin = InputPin;
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function FunctionLibrary_WeatherSys.FunctionLibrary_WeatherSys_C.SetupConfigToSkyLight
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkyLight*                        SkyLight                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FS_Candela&                CandelaParam                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UFunctionLibrary_WeatherSys_C::SetupConfigToSkyLight(class ASkyLight* SkyLight, const struct FS_Candela& CandelaParam, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FunctionLibrary_WeatherSys_C", "SetupConfigToSkyLight");

	Params::FunctionLibrary_WeatherSys_C_SetupConfigToSkyLight Parms{};

	Parms.SkyLight = SkyLight;
	Parms.CandelaParam = std::move(CandelaParam);
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}

}

