#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PaperMeshGrass

#include "Basic.hpp"


namespace SDK::Params
{

// Function PaperMeshGrass.PaperMeshGrassMeshComponent.SetGrassGenerateTextures
// 0x0010 (0x0010 - 0x0000)
struct PaperMeshGrassMeshComponent_SetGrassGenerateTextures final
{
public:
	TArray<class UTexture2D*>                     InTextures;                                        // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PaperMeshGrassMeshComponent_SetGrassGenerateTextures) == 0x000008, "Wrong alignment on PaperMeshGrassMeshComponent_SetGrassGenerateTextures");
static_assert(sizeof(PaperMeshGrassMeshComponent_SetGrassGenerateTextures) == 0x000010, "Wrong size on PaperMeshGrassMeshComponent_SetGrassGenerateTextures");
static_assert(offsetof(PaperMeshGrassMeshComponent_SetGrassGenerateTextures, InTextures) == 0x000000, "Member 'PaperMeshGrassMeshComponent_SetGrassGenerateTextures::InTextures' has a wrong offset!");

}

