#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PaperSkelMeshBaker

#include "Basic.hpp"

#include "PaperSkelMeshBaker_classes.hpp"
#include "PaperSkelMeshBaker_parameters.hpp"


namespace SDK
{

// Function PaperSkelMeshBaker.PaperSkelMeshBakeLibrary.ForceRefreshAnimation
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class USkeletalMeshComponent*           InSkeletalMeshComponent                                (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPaperSkelMeshBakeLibrary::ForceRefreshAnimation(class USkeletalMeshComponent* InSkeletalMeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PaperSkelMeshBakeLibrary", "ForceRefreshAnimation");

	Params::PaperSkelMeshBakeLibrary_ForceRefreshAnimation Parms{};

	Parms.InSkeletalMeshComponent = InSkeletalMeshComponent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PaperSkelMeshBaker.PaperSkelMeshBakeLibrary.MergeSkeletalMeshComponentsAndSave
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    PackageName                                            (ConstParm, Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FPaperSkelMeshMergeParams& Params_0                                               (ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
// bool                                    bIsNeedSave                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USkeletalMesh*                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class USkeletalMesh* UPaperSkelMeshBakeLibrary::MergeSkeletalMeshComponentsAndSave(const class FString& PackageName, const struct FPaperSkelMeshMergeParams& Params_0, bool bIsNeedSave)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PaperSkelMeshBakeLibrary", "MergeSkeletalMeshComponentsAndSave");

	Params::PaperSkelMeshBakeLibrary_MergeSkeletalMeshComponentsAndSave Parms{};

	Parms.PackageName = std::move(PackageName);
	Parms.Params_0 = std::move(Params_0);
	Parms.bIsNeedSave = bIsNeedSave;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PaperSkelMeshBaker.PaperSkelMeshBakeLibrary.SwitchMergedMaterialBetweenMaskAndOpaque
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class USkeletalMeshComponent*           Component                                              (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bSwitchToMask                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPaperSkelMeshBakeLibrary::SwitchMergedMaterialBetweenMaskAndOpaque(class USkeletalMeshComponent* Component, bool bSwitchToMask)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PaperSkelMeshBakeLibrary", "SwitchMergedMaterialBetweenMaskAndOpaque");

	Params::PaperSkelMeshBakeLibrary_SwitchMergedMaterialBetweenMaskAndOpaque Parms{};

	Parms.Component = Component;
	Parms.bSwitchToMask = bSwitchToMask;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PaperSkelMeshBaker.PaperSkelMeshBakeLibrary.UpdateSkeletalMesh
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class USkeletalMeshComponent*           TargetComponent                                        (Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class USkeletalMesh*                    InSkeletalMesh                                         (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPaperSkelMeshBakeLibrary::UpdateSkeletalMesh(class USkeletalMeshComponent* TargetComponent, class USkeletalMesh* InSkeletalMesh)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PaperSkelMeshBakeLibrary", "UpdateSkeletalMesh");

	Params::PaperSkelMeshBakeLibrary_UpdateSkeletalMesh Parms{};

	Parms.TargetComponent = TargetComponent;
	Parms.InSkeletalMesh = InSkeletalMesh;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

