#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PSDKLogin

#include "Basic.hpp"

#include "PSDKLogin_classes.hpp"
#include "PSDKLogin_parameters.hpp"


namespace SDK
{

// Function PSDKLogin.PSdkHyperlinkDecorator.ClickFun
// (Native, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TMap<class FString, class FString>&MetaData                                               (ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)

void UPSdkHyperlinkDecorator::ClickFun(const TMap<class FString, class FString>& MetaData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSdkHyperlinkDecorator", "ClickFun");

	Params::PSdkHyperlinkDecorator_ClickFun Parms{};

	Parms.MetaData = std::move(MetaData);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

