#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ROLE_XinYuanShuLinHillside_Sunrise

#include "Basic.hpp"

#include "ROLE_WorldBase_Sunrise_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ROLE_XinYuanShuLinHillside_Sunrise.ROLE_XinYuanShuLinHillside_Sunrise_C
// 0x0000 (0x0158 - 0x0158)
class UROLE_XinYuanShuLinHillside_Sunrise_C final : public UROLE_WorldBase_Sunrise_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ROLE_XinYuanShuLinHillside_Sunrise_C">();
	}
	static class UROLE_XinYuanShuLinHillside_Sunrise_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UROLE_XinYuanShuLinHillside_Sunrise_C>();
	}
};
static_assert(alignof(UROLE_XinYuanShuLinHillside_Sunrise_C) == 0x000008, "Wrong alignment on UROLE_XinYuanShuLinHillside_Sunrise_C");
static_assert(sizeof(UROLE_XinYuanShuLinHillside_Sunrise_C) == 0x000158, "Wrong size on UROLE_XinYuanShuLinHillside_Sunrise_C");

}

