#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TOD_XinYuanShuLinFlower_Morning

#include "Basic.hpp"

#include "TOD_WorldBase_Morning_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TOD_XinYuanShuLinFlower_Morning.TOD_XinYuanShuLinFlower_Morning_C
// 0x0000 (0x0A48 - 0x0A48)
class UTOD_XinYuanShuLinFlower_Morning_C final : public UTOD_WorldBase_Morning_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TOD_XinYuanShuLinFlower_Morning_C">();
	}
	static class UTOD_XinYuanShuLinFlower_Morning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTOD_XinYuanShuLinFlower_Morning_C>();
	}
};
static_assert(alignof(UTOD_XinYuanShuLinFlower_Morning_C) == 0x000008, "Wrong alignment on UTOD_XinYuanShuLinFlower_Morning_C");
static_assert(sizeof(UTOD_XinYuanShuLinFlower_Morning_C) == 0x000A48, "Wrong size on UTOD_XinYuanShuLinFlower_Morning_C");

}

