#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TOD_XinYuanShuLinTree_Night

#include "Basic.hpp"

#include "TOD_WorldBase_Night_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TOD_XinYuanShuLinTree_Night.TOD_XinYuanShuLinTree_Night_C
// 0x0000 (0x0A48 - 0x0A48)
class UTOD_XinYuanShuLinTree_Night_C final : public UTOD_WorldBase_Night_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TOD_XinYuanShuLinTree_Night_C">();
	}
	static class UTOD_XinYuanShuLinTree_Night_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTOD_XinYuanShuLinTree_Night_C>();
	}
};
static_assert(alignof(UTOD_XinYuanShuLinTree_Night_C) == 0x000008, "Wrong alignment on UTOD_XinYuanShuLinTree_Night_C");
static_assert(sizeof(UTOD_XinYuanShuLinTree_Night_C) == 0x000A48, "Wrong size on UTOD_XinYuanShuLinTree_Night_C");

}

