#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Level_Unlock_System

#include "Basic.hpp"

#include "WBP_Level_Unlock_System_classes.hpp"
#include "WBP_Level_Unlock_System_parameters.hpp"


namespace SDK
{

// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.OnListItemValueChangedViaIndex
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Level_Unlock_System_C::OnListItemValueChangedViaIndex(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "OnListItemValueChangedViaIndex");

	Params::WBP_Level_Unlock_System_C_OnListItemValueChangedViaIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.OnListItemObjectSetViaIndex
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Level_Unlock_System_C::OnListItemObjectSetViaIndex(int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "OnListItemObjectSetViaIndex");

	Params::WBP_Level_Unlock_System_C_OnListItemObjectSetViaIndex Parms{};

	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.ExecuteUbergraph_WBP_Level_Unlock_System
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Level_Unlock_System_C::ExecuteUbergraph_WBP_Level_Unlock_System(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "ExecuteUbergraph_WBP_Level_Unlock_System");

	Params::WBP_Level_Unlock_System_C_ExecuteUbergraph_WBP_Level_Unlock_System Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Level_Unlock_System_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "BP_OnItemSelectionChanged");

	Params::WBP_Level_Unlock_System_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Level_Unlock_System_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "BP_OnItemExpansionChanged");

	Params::WBP_Level_Unlock_System_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Level_Unlock_System.WBP_Level_Unlock_System_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UWBP_Level_Unlock_System_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Level_Unlock_System_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}

}

