#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SysHUD_OnlineButton

#include "Basic.hpp"

#include "WBP_SysHUD_OnlineButton_classes.hpp"
#include "WBP_SysHUD_OnlineButton_parameters.hpp"


namespace SDK
{

// Function WBP_SysHUD_OnlineButton.WBP_SysHUD_OnlineButton_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UWBP_SysHUD_OnlineButton_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SysHUD_OnlineButton_C", "GetModuleName");

	Params::WBP_SysHUD_OnlineButton_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

